---
configs:
  use: 'virtualbox'
  virtualbox:
    app:
      memory: 1024
      public_ip: '192.168.5.200'
    postgres:
      memory: 512
      public_ip: '192.168.5.201'
      private_ip: '192.168.0.13'
    mongodb:
      memory: 512
      public_ip: '192.168.5.202'
      private_ip: '192.168.0.14'
    rabbitmq:
      memory: 512
      public_ip: '192.168.5.203'
      private_ip: '192.168.0.15'
    nginx:
      memory: 512
      public_ip: '192.168.5.204'
    elasticsearch:
      memory: 1024
      public_ip: '192.168.5.205'
      private_ip: '192.168.0.12'

