package com.dataparse.server.service.notification;

public enum EventType {
    CREATE_FILE,
    EDIT_FILE,
    DELETE_FILE,

    EXPORT_START,
    EXPORT_PROGRESS,
    EXPORT_COMPLETE,

    FLOW_EXEC_START,
    FLOW_EXEC_PROGRESS,
    FLOW_EXEC_COMPLETE,

    REQUEST_APPLIED,
    FILTER_REFRESH,
    FILTERS_TO_REFRESH,

    TAB_STATE_CHANGED,
    VIZ_STATE_CHANGED,
    INGEST_STATE_CHANGED,
    USER_STATE_CHANGED,

    VIEW_DATADOC,
    DATADOC_VIEWED,
    DATADOC_NAME_CHANGED,

    TAB_ADDED,
    TAB_REMOVED,
    TAB_NAME_CHANGED,
    TAB_POSITION_CHANGED
}
