FROM ubuntu:17.10

MAINTAINER Tuan Nguyen <tuan08@gmail.com>

EXPOSE 22

RUN apt-get update
RUN apt-get install -y openssh-server
#ENTRYPOINT ["bootstrap.sh"]
#CMD ["/usr/sbin/sshd", "-D", "-f", "/etc/ssh/sshd_config"]

